### ISSUE TITLE
Classify Text exmaples

### ISSUE THREAD

**Issue by bararchy** [gbuesing/neural-net-ruby#1]
Is there a way to make this lib predict text classifications ? 
Very much like byes-classifiers but using a pre-ran learning phase with 2 data sets ?

**Comment by gbuesing** [comment]
You should be able to use this net to do text classification. You'd need to encode your text samples into an acceptable input format, using a bag-of-words encoding (I've rolled up a simple Ruby bag implementation here: https://github.com/gbuesing/kmeans-clusterer/blob/master/examples/utils/bag.rb )

If you have just 2 classes -- e.g spam/not-spam -- you can use a single output neuron, and encode your training set labels as either a 0 (not-spam) or 1 (spam).

If you're able to get this to work, I'd be interested in hearing about the results!

**Comment by bararchy** [comment]
@gbuesing 

Ok, so I setup a new repo here -> https://github.com/bararchy/ruby-ann-webattack-filtering

I did a few changes to word bag to allow the matrix to be created from my data set.
I get a matrix output that looks like this:

``` ruby
NMatrix.float(47,888): 
[ [ 2.77159, 1.02841, 0.534125, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ... ], 
  [ 0.0, 0.890631, 0.925131, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ... ], 
  [ 0.0, 0.890631, 0.925131, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ... ], 
  [ 0.0, 0.890631, 0.925131, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ... ], 
  [ 0.0, 0.890631, 0.925131, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ... ], 
  [ 0.0, 0.890631, 0.925131, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ... ], 
  [ 0.0, 0.890631, 0.925131, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ... ], 
  [ 0.0, 0.890631, 0.925131, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ... ], 
  [ 0.0, 0.890631, 0.925131, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ... ], 
  [ 0.0, 0.890631, 0.925131, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ... ], 
 ...
```

And I know from this I need to somehow have a 3 objects array that ANN accepts.
How should I proceed ?
