### ISSUE TITLE
RubyML

### ISSUE THREAD

**Issue by arbox** [gbuesing/neural-net-ruby#5]
Dear Geoff,

we've recently added `neural-net-ruby` to our RubyML list: https://github.com/arbox/machine-learning-with-ruby

In order to connect all Ruby & ML related projects we introduced the `rubyml` topic on GitHub.

Please cosider adding the `rubyml` topic to this repository as well so that the Ruby community can discover `neural-net-ruby` faster :smiley: 

Thank you in advance!

**Comment by gbuesing** [comment]
Done 😀

**Comment by arbox** [comment]
Awesome :+1:
